#!/bin/bash
set -e

POSTGRESQL_USER=${POSTGRESQL_USER:-"postgres"}
POSTGRESQL_PASS=${POSTGRESQL_PASS:-"postgres"}
POSTGRESQL_DB=${POSTGRESQL_DB:-"docker"}
POSTGRESQL_ENC=${POSTGRESQL_ENC:-"SQL_ASCII"}
POSTGRESQL_ENC=${POSTGRESQL_ENC:-"UTF-8"}

POSTGRESQL_TEMPLATE=${POSTGRESQL_TEMPLATE:-"DEFAULT"}

TZ=${TZ:-"UTC"}

PG_MAJOR=${PG_MAJOR:-"8.1"}

if [ -e /etc/redhat-release ]; then
    POSTGRESQL_BIN=/usr/bin/postgres
    POSTGRESQL_INITDB=/usr/bin/initdb
    POSTGRESQL_DATA=/var/lib/pgsql/data
    POSTGRESQL_CONFIG_FILE=${POSTGRESQL_DATA}/postgresql.conf

    # Template files overwritten from Dockerfile
    TEMPLATE_PG_CONFIG_FILE=/var/lib/pgsql/template/postgresql.conf
    TEMPLATE_PG_HBA_FILE=/var/lib/pgsql/template/pg_hba.conf
else
    POSTGRESQL_BIN=/usr/lib/postgresql/8.4/bin/postgres
    POSTGRESQL_INITDB=/usr/lib/postgresql/8.4/bin/initdb
    POSTGRESQL_DATA=/var/lib/postgresql/8.4/main
    POSTGRESQL_CONFIG_FILE=/etc/postgresql/8.4/main/postgresql.conf
fi

echo -e "\n# $(date)'" >> $TEMPLATE_PG_CONFIG_FILE
echo -e "\ntimezone = '$TZ'" >> $TEMPLATE_PG_CONFIG_FILE

#
# Prior to Postgres Initialisation we should have modified the 
# postgresql.conf file with customisations.
#
if [ ! -n "$(ls -A $POSTGRESQL_DATA)" ]; then
    echo "Directory is empty or non existent (creating '${POSTGRESQL_DATA}' now."

    mkdir -p $POSTGRESQL_DATA
    chown postgres:postgres $POSTGRESQL_DATA
    chmod 700 $POSTGRESQL_DATA
    sudo -u postgres $POSTGRESQL_INITDB -D $POSTGRESQL_DATA -E "$POSTGRESQL_ENC"
    
    sudo cp -f $TEMPLATE_PG_CONFIG_FILE $POSTGRESQL_DATA/
    sudo cp -f $TEMPLATE_PG_HBA_FILE $POSTGRESQL_DATA/

    chown postgres:postgres $POSTGRESQL_DATA/*
    chmod 700 $POSTGRESQL_DATA/*
    
    # certs not for centos
    [ -e /etc/redhat-release ] || ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem $POSTGRESQL_DATA/server.crt
    [ -e /etc/redhat-release ] || ln -s /etc/ssl/private/ssl-cert-snakeoil.key $POSTGRESQL_DATA/server.key

    # --single not support in 8.1
    POSTGRESQL_SINGLE="sudo -u postgres $POSTGRESQL_BIN --config-file=$TEMPLATE_PG_CONFIG_FILE"

    $POSTGRESQL_SINGLE <<< "CREATE USER $POSTGRESQL_USER WITH SUPERUSER;" > /dev/null
    $POSTGRESQL_SINGLE <<< "ALTER USER $POSTGRESQL_USER WITH PASSWORD '$POSTGRESQL_PASS';" > /dev/null
    $POSTGRESQL_SINGLE <<< "CREATE DATABASE $POSTGRESQL_DB OWNER $POSTGRESQL_USER TEMPLATE $POSTGRESQL_TEMPLATE;" > /dev/null
else
    echo "Files found at ${POSTGRESQL_DATA} ... assuming existing database."
fi

if [ "${PG_MAJOR}" == '8.1' ]; then
    exec sudo -u postgres /usr/bin/postmaster -D $POSTGRESQL_DATA
else
    exec sudo -u postgres $POSTGRESQL_BIN --config-file=$POSTGRESQL_CONFIG_FILE
fi
